// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/open/open.d.ts
declare module 'open' {
	function open(target: string, app?: string): void;
	export = open;
}
